# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d718c53e36553f9f189651dbf57cd0b71e75b8e0b00358aa0b4635bd9fca5941b3e2cb3934ca6dc5598111c8a4590797fe1f78c4e9f391be1b9e55b8c21e0939

test:
  secret_key_base: e5bd88ceecea4d053b0722cc73de8f299776bde63b2ee15d4a5a153e4b8396e13740228a26784df09758a7ce25f861891baba443b76afb793243af8d18c3a704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
